<a href="https://colab.research.google.com/github/mireiacarbo/03MIAR---Algoritmos-de-Optimizacion/blob/main/Trabajo_Pr%C3%A1ctico_Algoritmos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Algoritmos de optimización - Trabajo Práctico<br>
Nombre y Apellidos: Mireia Carbó Feliu  <br>
Url: https://github.com/mireiacarbo/03MIAR---Algoritmos-de-Optimizacion/blob/main/TrabajoPractico<br>
Google Colab: https://colab.research.google.com/drive/15p10kpWODiCAgoYfzcyAx0sza9GYF8Yw?usp=sharing<br>


Problema:

>**3. Configuración de Tribunales** <br>
Se precisa configurar tribunales de evaluación para un grupo de 15 alumnos que desean presentar su Trabajo Fin de Máster (TFM). Cada tribunal está compuesto por tres profesores, cada uno desempeñando uno de los siguientes roles: Presidente, Secretario o Vocal.

>Los profesores han indicado su disponibilidad horaria para participar en los tribunales de 15h a 21h durante la semana del 15 al 19 de abril.

>Hay 15 alumnos, por lo que se deben configurar 15 tribunales buscando la configuración más equilibrada posible en cuanto a la cantidad de tribunales asignados a cada profesor, es decir, evitando que un profesor tenga muchos tribunales y otros pocos. Obviamente ningún profesor puede asistir a dos tribunales a la misma fecha/hora y no puede ser convocado a un tribunal al que no tiene disponibilidad.





#Datos clave del problema:

- **Profesores**: 10
- **Tribunales**: 15
- Cada tribunal tiene **3 roles**: Presidente, Secretario y Vocal.
- **Disponibilidad horaria**: De 15h a 21h del 15 al 19 de abril.
- **Matriz de disponibilidad**:
  - 1 indica que el profesor está disponible en esa franja horaria.
  - 0 indica que no está disponible.
- **Objetivo**: Equilibrar la carga de trabajo entre profesores evitando asignaciones desiguales.
- **Restricciones**:
  - Un profesor no puede estar en dos tribunales al mismo tiempo.
  - Solo puede ser asignado si está disponible en esa franja horaria.
  - Debe haber una repartición equitativa de los profesores en los diferentes tribunales.

#Modelo
- **¿Como represento el espacio de soluciones?**

  El espacio de soluciones está compuesto por todas las posibles asignaciones de los 10 profesores a los 15 tribunales, asegurando que cada tribunal tenga exactamente 3 profesores cubriendo cada uno de los roles(Presidente, secretario y vocal).

  El espacio de soluciones lo podemos representar mediante una matriz de asignación, donde las filas son los 15 tribunales y las columnas contienen la información necesaria de cada tribunal: dia, hora, profesoren su respectivo rol.

- **¿Cual es la función objetivo?**

  El objetivo principal es repartir de forma equitativa a los 10 profesores en los diferentes tribunales, evitando que algunos tengan muchas asignaciones y otros pocas.

  Por tanto, la función objetivo es minimizar la diferencia entre el profesor con mñas tribunales asignados y el profesor con menos tribunales asignados, buscando una distribución justa.

  Definimos: Sea $T_i$= número total de tribunales en los que participa el profesor $i$, entonces la **función objetivo** es $min(max(T_i)-min(T_i))$


- **¿Como implemento las restricciones?**

  Para garantizar que la solución sea válida, debemos cumplir las siguientes restricciones:

  * **Cada tribunal tiene exactamente 3 profesores con roles definidos:** Para cada tribunal $j$ debemos garantizar que haya exactamente un profesor de cada rol. Para ello, utilizamos una matriz binaria de asignación  $x_{i,j,k}$, donde:
    * $i$ es el profesor.
    * $j$ es el tribunal.
    * $k$ es el rol (Presidente, Secretario o Vocal).
    * $x_{i,j,k}=1$ si el profesor $i$ es asignado al tribunal $j$ con el rol $k$, $x_{i,j,k}=0$ en caso contrario.
  
    Por tanto, la restricción será que se cumpla la siguiente ecuación: $ \sum_{i=1}^{10} x_{i,j,k} = 1, \forall j \in [1, 15], \forall k \in \{\text{Presidente, Secretario, Vocal}\} $
    
  * **Disponibilidad horaria:** Un profesor solo puede ser asignado si está disponible en esa fecha y hora.

    Si la disponibilidad está en una matriz $D[i,j]$, donde $D[i,j]=1$ si el profesor $i$ puede estar en el tribunal $j$, entonces: $x_{i,j,k} \leqslant D_{i,j}, \forall i,j,k $. Si $D_{i,j}=0$, entonces $x_{i,j,k} \neq 1$

  * **No solapamiento de horarios:** Si dos tribunales coinciden en hora, un profesor no puede estar en ambos.

    Definimos $H_{i}$ como el conjunto de tribunales que son a la misma hora $t$, y la restricción que nos asegura que el profesor $i$ no puede estar en dos tribunales al mismo tiempo:  $ \sum_{j \in H_t} x_{i,j,k} \leqslant 1, \forall i,t $.
  
  * **Distribución equitativa de carga:** Queremos que la diferencia entre el profesor con más tribunales asignados y el que tiene menos sea mínima, es decir, que todos los profesores esten aproximadamente en el mismo número de tribunales.
  
    Definimos como $T_i$ el número total de tribunales en los que participa el profesor $i$, donde $T_i = \sum_{j=1}^{15} \sum_{k=1}^{3} x_{i,j,k}$

#Análisis
**¿Que complejidad tiene el problema? Orden de complejidad y Contabilizar el espacio de soluciones**

Cada tribunal necesita asignar 3 roles, y cada rol puede ser ocupado por cualquiera de los 10 profesores: $Total de variables =N×T×R=10×15×3=450$

Para analizar la complejidad del problema, debemos tener en cuenta la complejidad de las variables de decisión y restricciones definidas anteriormente.

Para resolver el problema se han seguido dos estratégias: Utilizando el algoritmo greedy y utilizando la libreria externa pulp (extra). Analizamos la complejidad para el primer caso.
- Restricción 1: Cada tribunal debe tener un profesor por cada rol. Se generan
 $T×R=15×3=45$ restricciones.
- Restricción 2: Un profesor solo puede ser asignado si está disponible y puede desempeñar el rol. Es decir, buscar los candidatos entre los profesores disponivles, lo que supone $O(N)$, donde N=10.
- Restricción 3: Balanceo de carga $O(N×logN)$, donde N=10.

Por tanto, en el peor caso el problema tiene una complejidad: $O(T×R×N×logN) = O(15×3×10×log10) = O(450)$

El espacio de soluciones representa la cantidad de maneras en que podemos asignar profesores a tribunales respetando las restricciones: $N^{(T×R)}=10^{(15×3)}=10^{45}$


#Diseño
**¿Que técnica utilizo? ¿Por qué?**

El problema planteado tiene un gran espacio de soluciones $10^{45}$, lo que hace que no sea muy viable la implementación de búsqueda exhaustiva o ILP en tiempos razonables. Es por ello que se ha omtado por implementar Greedy.

Es una técnica que nos permite asignar los profesores disponibles que puedan estan en un rol, balanceando la carga de trabajo, de una forma clara y que no tiene excesiva complejidad.

**PRIMERA OPCIÓN: Utilizando técnica Greedy**

Pasos del algoritmo:

1. Recorrer cada tribunal (de 1 a 15).
2. Para cada tribunal, recorrer los 3 roles (Presidente, Secretario y Vocal).
3. Filtrar los candidatos posibles, seleccionando los profesores disponibles en la franja horaria y que pueden desempeñar dicho roll.
4. Ordenar los candidatos disponibles según el número de tribunales en los que ya han sido asignados (balanceo de carga).
5. Seleccionar el candidato con menor carga de trabajo.
6. Asignar el profesor al tribunal y actualizar su carga de trabajo.

Repetimos este proceso hasta completar todos los tribunales.

In [ ]:
# IMPORTS
import pandas as pd
import time

In [ ]:
# CARGA DE DATOS
archivo_excel = "Datos_problema_Tribunales.xlsx"
disponibilidad_df = pd.read_excel(archivo_excel, sheet_name="disponibilidad", index_col=1, header=[0,1])
roles_df = pd.read_excel(archivo_excel, sheet_name="roles", index_col=0)

In [ ]:
# Reformateamos la matriz de disponibilidad
profesores = disponibilidad_df.index.tolist()
dias = disponibilidad_df.columns.unique(level=0).tolist()[1:]
horas = disponibilidad_df.columns.get_level_values(1).unique().tolist()[1:]

In [ ]:
# MATRIZ DE DISPONIBILIDAD SIMPLIFICADA
franjas_horarias = [f"{dia}_{hora}" for dia in dias for hora in horas]
disponibilidad_simple = pd.DataFrame(index=profesores, columns=franjas_horarias)

for profesor in profesores:
    for dia in dias:
        for hora in horas:
            franja = f"{dia}_{hora}"
            disponibilidad_simple.loc[profesor, franja] = disponibilidad_df.loc[profesor, (dia, hora)]

disponibilidad = disponibilidad_simple.to_numpy().astype(int)

In [ ]:
# MATRIZ DE ROLES
rol_nombres = ['Presidente', 'Secretario', 'Vocal']
roles = pd.DataFrame(0, index=profesores, columns=rol_nombres).to_numpy().astype(int)

for i, profesor in enumerate(profesores):
    roles_str = roles_df.loc[profesor, 'ROL']
    if 'P' in roles_str:
        roles[i, 0] = 1
    if 'S' in roles_str:
        roles[i, 1] = 1
    if 'V' in roles_str:
        roles[i, 2] = 1


In [ ]:
# VARIABLES
num_profesores = len(profesores)
num_tribunales = 15
num_roles = len(rol_nombres)
tribunal_franjas = [(dia, hora) for dia in dias for hora in horas][:num_tribunales]
carga_profesores = [0] * num_profesores

In [ ]:
# FUNCIÓN GREEDY
def asignar_tribunales():
    asignacion = []
    for j in range(num_tribunales):
        dia, hora = tribunal_franjas[j]
        franja_index = franjas_horarias.index(f"{dia}_{hora}")
        tribunal = []

        for k in range(num_roles):
            candidatos = [i for i in range(num_profesores) if disponibilidad[i][franja_index] == 1 and roles[i][k] == 1]
            if not candidatos:
                return None  # No hay solución válida

            candidatos.sort(key=lambda x: carga_profesores[x])  # Balanceo de carga
            elegido = candidatos[0]
            tribunal.append(elegido)
            carga_profesores[elegido] += 1

        asignacion.append(tribunal)

    return asignacion

In [ ]:
# TIEMPO DE EJECUCIÓN
start_time = time.time()
asignacion_final = asignar_tribunales()
end_time = time.time()


In [27]:
# RESULTADO
def imprimir_asignacion(asignacion):
    if not asignacion:
        print("No se ha encontrado una asignación válida.")
        return
    for j, tribunal in enumerate(asignacion):
        dia, hora = tribunal_franjas[j]
        print(f"Tribunal {j + 1} - Fecha: {dia}, Hora: {hora}")
        for k, profesor in enumerate(tribunal):
            print(f"  {rol_nombres[k]}: {profesores[profesor]}")
        print("-")

imprimir_asignacion(asignacion_final)
print(f"Tiempo de ejecución: {end_time - start_time:.4f} segundos")

Tribunal 1 - Fecha: 15, Hora: 15
  Presidente: QYV
  Secretario: HLC
  Vocal: MSB
-
Tribunal 2 - Fecha: 15, Hora: 16
  Presidente: RRD
  Secretario: PMQ
  Vocal: QWF
-
Tribunal 3 - Fecha: 15, Hora: 17
  Presidente: LHL
  Secretario: EBB
  Vocal: IOE
-
Tribunal 4 - Fecha: 15, Hora: 18
  Presidente: IOA
  Secretario: RRD
  Vocal: QYV
-
Tribunal 5 - Fecha: 15, Hora: 19
  Presidente: PMQ
  Secretario: HLC
  Vocal: QWF
-
Tribunal 6 - Fecha: 15, Hora: 20
  Presidente: LHL
  Secretario: MSB
  Vocal: IOE
-
Tribunal 7 - Fecha: 15, Hora: 21
  Presidente: IOA
  Secretario: RRD
  Vocal: LHL
-
Tribunal 8 - Fecha: 16, Hora: 15
  Presidente: MSB
  Secretario: EBB
  Vocal: HLC
-
Tribunal 9 - Fecha: 16, Hora: 16
  Presidente: QYV
  Secretario: PMQ
  Vocal: QWF
-
Tribunal 10 - Fecha: 16, Hora: 17
  Presidente: IOE
  Secretario: RRD
  Vocal: QYV
-
Tribunal 11 - Fecha: 16, Hora: 18
  Presidente: PMQ
  Secretario: EBB
  Vocal: HLC
-
Tribunal 12 - Fecha: 16, Hora: 19
  Presidente: MSB
  Secretario: QWF
  Vo

In [28]:
# DISTRIBUCION DE LA CARGA
def imprimir_distribucion():
    print("\nDistribución de carga de trabajo por profesor:")
    for i, profesor in enumerate(profesores):
        print(f"{profesor}: {carga_profesores[i]} tribunales")

imprimir_distribucion()


Distribución de carga de trabajo por profesor:
RRD: 5 tribunales
QYV: 5 tribunales
LHL: 5 tribunales
HLC: 4 tribunales
MSB: 5 tribunales
PMQ: 5 tribunales
QWF: 4 tribunales
EBB: 4 tribunales
IOE: 4 tribunales
IOA: 4 tribunales


**SEGUNDA OPCIÓN: Utilizando una libreria externa**

In [ ]:
!pip install pulp

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 17.7/17.7 MB 39.6 MB/s eta 0:00:00


In [ ]:
#IMPORTS
import pandas as pd
from pulp import LpProblem, LpVariable, lpSum, LpMinimize, LpBinary

In [ ]:
#CARGA DE DATOS
archivo_excel = "Datos_problema_Tribunales.xlsx"
disponibilidad_df = pd.read_excel(archivo_excel, sheet_name="disponibilidad", index_col=1, header=[0,1])
roles_df = pd.read_excel(archivo_excel, sheet_name="roles", index_col=0)

In [ ]:
# Reformateamos la matriz de disponibilidad
profesores = disponibilidad_df.index.tolist()
dias = disponibilidad_df.columns.unique(level=0).tolist()[1:]
horas = disponibilidad_df.columns.get_level_values(1).unique().tolist()[1:]

In [ ]:
# MATRIZ DE DISPONIBILIDAD SIMPLIFICADA (profesores x franjas horarias)
franjas_horarias = [f"{dia}_{hora}" for dia in dias for hora in horas]
disponibilidad_simple = pd.DataFrame(index=profesores, columns=franjas_horarias)

for profesor in profesores:
    for dia in dias:
        for hora in horas:
            franja = f"{dia}_{hora}"
            disponibilidad_simple.loc[profesor, franja] = disponibilidad_df.loc[profesor, (dia, hora)]

print(disponibilidad_simple)

    15_15 15_16 15_17 15_18 15_19 15_20 15_21 16_15 16_16 16_17  ... 18_19  \
RRD     0     1     1     1     0     1     1     1     0     1  ...     1   
QYV     1     1     1     1     0     0     0     0     1     1  ...     1   
LHL     0     0     1     1     0     1     1     1     1     1  ...     1   
HLC     1     0     1     0     1     1     0     1     0     0  ...     0   
MSB     1     1     0     1     0     1     1     1     1     1  ...     0   
PMQ     1     1     1     1     1     0     0     1     1     1  ...     0   
QWF     0     1     1     1     1     1     1     1     1     0  ...     0   
EBB     1     1     1     1     1     0     0     1     1     0  ...     1   
IOE     1     0     1     1     0     1     0     0     1     1  ...     1   
IOA     1     1     0     1     1     0     1     1     0     0  ...     1   

    18_20 18_21 19_15 19_16 19_17 19_18 19_19 19_20 19_21  
RRD     1     1     1     1     1     1     1     0     0  
QYV     1     1     1

In [ ]:
disponibilidad = disponibilidad_simple.to_numpy().astype(int)
print(disponibilidad)

[[0 1 1 1 0 1 1 1 0 1 1 1 1 1 1 1 0 0 1 0 1 0 1 1 1 1 1 1 1 1 1 1 1 0 0]
 [1 1 1 1 0 0 0 0 1 1 1 1 0 0 1 0 0 1 1 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1]
 [0 0 1 1 0 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 1 0 1 0 1 1 0 1 0 1]
 [1 0 1 0 1 1 0 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 0 1 1 0 1 1 1 1 1 1 1 1 0]
 [1 1 0 1 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 1 0 1 1 1 0 1 1 1 0 1 1 1 1 0]
 [1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 0 0 1 1 1 1 1 0 1 0 1]
 [0 1 1 1 1 1 1 1 1 0 1 1 0 1 0 0 1 1 0 0 1 1 0 0 0 0 1 1 1 1 1 1 1 0 1]
 [1 1 1 1 1 0 0 1 1 0 1 1 1 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 0 1 0]
 [1 0 1 1 0 1 0 0 1 1 1 1 1 1 1 1 0 0 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1]
 [1 1 0 1 1 0 1 1 0 0 0 0 0 1 1 1 0 0 1 1 1 1 0 0 1 1 1 1 1 1 1 0 0 0 1]]


In [ ]:
# MATRIZ DE ROLES
rol_nombres = ['Presidente', 'Secretario', 'Vocal']
roles = pd.DataFrame(0, index=profesores, columns=rol_nombres).to_numpy().astype(int)

for i, profesor in enumerate(profesores):
    roles_str = roles_df.loc[profesor, 'ROL']
    if 'P' in roles_str:
        roles[i, 0] = 1
    if 'S' in roles_str:
        roles[i, 1] = 1
    if 'V' in roles_str:
        roles[i, 2] = 1

print(roles)

[[1 1 1]
 [1 1 1]
 [1 0 1]
 [0 1 1]
 [1 1 1]
 [1 1 1]
 [0 1 1]
 [0 1 1]
 [1 1 1]
 [1 1 1]]


In [ ]:
# VARIABLES
num_profesores = len(profesores)
num_tribunales = 15
num_roles = len(rol_nombres)
num_franjas = len(franjas_horarias)
tribunal_franjas = [(dia, hora) for dia in dias for hora in horas][:num_tribunales]

# Variables de decisión
x = {(i, j, k): LpVariable(f"x_{i}_{j}_{k}", cat=LpBinary)
     for i in range(num_profesores)
     for j in range(num_tribunales)
     for k in range(num_roles)}

In [ ]:
# MODELO DE OPTIMIZACIÓN
problema = LpProblem("Configuracion_de_Tribunales", LpMinimize)

In [ ]:
# Variables de la carga de trabajo
T_max = LpVariable("T_max", lowBound=0, cat="Integer")
T_min = LpVariable("T_min", lowBound=0, cat="Integer")
T = {i: lpSum(x[i, j, k] for j in range(num_tribunales) for k in range(num_roles))
     for i in range(num_profesores)}

In [ ]:
# RESTRICCIONES (declaradas anteriormente)
problema_res1 = restriccion_1(num_tribunales, num_roles, num_profesores, lpSum, problema)
problema_res2 = restriccion_2(num_profesores, num_tribunales, num_roles, disponibilidad, roles, problema_res1)
problema_res3 = restriccion_3(num_profesores, T, T_max, T_min, problema_res2)

In [ ]:
# FUNCIÓN OBJETIVO: minimizar la diferencia de carga de trabajo
problema_res3 += T_max - T_min

# Resolver el problema
problema_res3.solve()

1

In [ ]:
# RESULTADO
for j in range(num_tribunales):
    dia, hora = tribunal_franjas[j]
    print(f"Tribunal {j + 1} - Fecha: {dia}, Hora: {hora}")
    for k, role in enumerate(rol_nombres):
        assigned_professor = [i for i in range(num_profesores) if x[i, j, k].varValue == 1]
        print(f"  {role}: {profesores[assigned_professor[0]] if assigned_professor else 'N/A'}")
    print("-")

#df_resultados.head(15)

Tribunal 1 - Fecha: 15, Hora: 15
  Presidente: QYV
  Secretario: EBB
  Vocal: IOE
-
Tribunal 2 - Fecha: 15, Hora: 16
  Presidente: QYV
  Secretario: EBB
  Vocal: IOA
-
Tribunal 3 - Fecha: 15, Hora: 17
  Presidente: RRD
  Secretario: QYV
  Vocal: QYV
-
Tribunal 4 - Fecha: 15, Hora: 18
  Presidente: RRD
  Secretario: IOA
  Vocal: QWF
-
Tribunal 5 - Fecha: 15, Hora: 19
  Presidente: IOA
  Secretario: HLC
  Vocal: IOA
-
Tribunal 6 - Fecha: 15, Hora: 20
  Presidente: IOE
  Secretario: IOE
  Vocal: IOE
-
Tribunal 7 - Fecha: 15, Hora: 21
  Presidente: LHL
  Secretario: QWF
  Vocal: IOA
-
Tribunal 8 - Fecha: 16, Hora: 15
  Presidente: PMQ
  Secretario: MSB
  Vocal: EBB
-
Tribunal 9 - Fecha: 16, Hora: 16
  Presidente: MSB
  Secretario: PMQ
  Vocal: QWF
-
Tribunal 10 - Fecha: 16, Hora: 17
  Presidente: LHL
  Secretario: MSB
  Vocal: LHL
-
Tribunal 11 - Fecha: 16, Hora: 18
  Presidente: PMQ
  Secretario: QYV
  Vocal: QWF
-
Tribunal 12 - Fecha: 16, Hora: 19
  Presidente: PMQ
  Secretario: RRD
  Vo

In [ ]:
# Carga de trabajo
total_carga = {profesores[i]: sum(x[i, j, k].varValue for j in range(num_tribunales) for k in range(num_roles))
               for i in range(num_profesores)}
print("Carga de trabajo por profesor:", total_carga)

Carga de trabajo por profesor: {'RRD': 5.0, 'QYV': 5.0, 'LHL': 4.0, 'HLC': 4.0, 'MSB': 4.0, 'PMQ': 5.0, 'QWF': 4.0, 'EBB': 4.0, 'IOE': 5.0, 'IOA': 5.0}
